baseurl = "/"
title = "Universal"
theme = "universal"

languageCode = "en-us"
# Site language. Available translations in the theme's `/i18n` directory.
defaultContentLanguage = "en-us"

uglyURLs = true
buildFuture = true

# Define the number of posts per page
paginate = 10


[languages]

[languages.en-us]
    languageCode = "en-us"
    contentDir = "content/en-us"

[languages.zh-cn]
    languageCode = "zh-cn"
    contentDir = "content/zh-cn"


[[menu.main]]
    identifier="download"
    name = "Download"
    url  = "/download.html"
    weight = 1

[[menu.main]]
    identifier="documentation"
    name = "Documentation"
    url  = "/docs/example/collapsed.html"
    weight = 2

[[menu.main]]
    identifier = "community"
    name = "Community"
    weight = 3
    hasChildren = true

[[menu.main]]
    identifier = "contribution"
    name = "Contribution"
    url  = "/contribution.html"
    weight = 1
    parent = 'community'

[[menu.main]]
    identifier = "who-we-are"
    name = "Who we are"
    url  = "/who-we-are.html"
    weight = 2
    parent = 'community'

[[menu.main]]
    identifier = "communication"
    name = "Communication"
    url  = "/communication.html"
    weight = 3
    parent = 'community'

[[menu.main]]
    identifier = "newsroom"
    name = "Newsroom"
    weight = 4
    hasChildren = true


[[menu.main]]
    identifier = "sourcecode"
    name = "Source Code"
    weight = 4
    hasChildren = true

[[menu.main]]
    identifier = "gitee"
    name = "Gitee"
    url  = "/#"
    weight = 1
    parent = 'sourcecode'

[[menu.main]]
    identifier = "github"
    name = "Github"
    url  = "/#"
    weight = 2
    parent = 'sourcecode'

[[menu.main]]
    identifier = "events"
    name = "Events"
    url  = "/events.html"
    weight = 1
    parent = 'newsroom'

[[menu.main]]
    identifier = "news"
    name = "News"
    url  = "/news.html"
    weight = 2
    parent = 'newsroom'

    [[menu.main]]
    identifier = "blog"
    name = "Blog"
    url  = "/blog.html"
    weight = 3
    parent = 'newsroom'

[[menu.main]]
    identifier = "lang"
    name = "中文"
    url  = "/zh-cn"
    weight = 5


# Chinese Menu
[[languages.zh-cn.menu.main]]
    identifier="download"
    name = "下载"
    url  = "/zh-cn/download.html"
    weight = 1

[[languages.zh-cn.menu.main]]
    identifier="documentation"
    name = "文档"
    url  = "/zh-cn/docs/example/collapsed.html"
    weight = 2

[[languages.zh-cn.menu.main]]
    identifier = "community"
    name = "社区"
    weight = 3
    hasChildren = true

[[languages.zh-cn.menu.main]]
    identifier = "contribution"
    name = "贡献"
    url  = "/zh-cn/contribution.html"
    weight = 1
    parent = 'community'

[[languages.zh-cn.menu.main]]
    identifier = "who_we_are"
    name = "团队"
    url  = "/who_we_are.html"
    weight = 2
    parent = 'community'

[[languages.zh-cn.menu.main]]
    identifier = "communication"
    name = "交流"
    url  = "/communication.html"
    weight = 3
    parent = 'community'

[[languages.zh-cn.menu.main]]
    identifier = "newsroom"
    name = "活动"
    weight = 4
    hasChildren = true


[[languages.zh-cn.menu.main]]
    identifier = "sourcecode"
    name = "源码"
    weight = 4
    hasChildren = true

[[languages.zh-cn.menu.main]]
    identifier = "gitee"
    name = "Gitee"
    url  = "/#"
    weight = 1
    parent = 'sourcecode'

[[languages.zh-cn.menu.main]]
    identifier = "github"
    name = "Github"
    url  = "/#"
    weight = 2
    parent = 'sourcecode'

[[languages.zh-cn.menu.main]]
    identifier = "events"
    name = "活动"
    url  = "/event.html"
    weight = 1
    parent = 'newsroom'

[[languages.zh-cn.menu.main]]
    identifier = "news"
    name = "新闻"
    url  = "/news.html"
    weight = 2
    parent = 'newsroom'

    [[languages.zh-cn.menu.main]]
    identifier = "blog"
    name = "博客"
    url  = "/blog.html"
    weight = 3
    parent = 'newsroom'

[[languages.zh-cn.menu.main]]
    identifier = "lang"
    name = "EN"
    url  = "/en-us"
    weight = 5



[params]
    viewMorePostLink = "/blog/"
    author = "DevCows"
    defaultKeywords = ["devows", "hugo", "go"]
    mainSections = ["blog"]
    defaultDescription = "Site template made by devcows using hugo"
    email = "contact@openlookeng.io"


    # Style options: default (light-blue), blue, green, marsala, pink, red, turquoise, violet
    style = "default"

    about_us = "<p>Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas.</p>"

    provide = " "
    license = " "
    # Format dates with Go's time formatting
    date_format = "January 2, 2006"

    logo = "img/logo.png"
    logo_small = "img/logo-small.png"

[Permalinks]
    blog = "/blog/:year/:month/:day/:filename/"


# Enable and disable widgets for the right sidebar
[params.widgets]
    categories = true
    tags = true
    search = true



[params.recent_posts]
    enable = true
    title = "From our blog"
    subtitle = "Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vestibulum tortor quam, feugiat vitae, ultricies eget, tempor sit amet, ante. Donec eu libero sit amet quam egestas semper. Aenean ultricies mi vitae est. Mauris placerat eleifend leo."

#blog_single评论模块新增
# Valine.
  # You can get your appid and appkey from https://leancloud.cn
  # more info please open https://valine.js.org
  [params.valine]
    enable = true
    appId = 'KcTcd38EvA1I33vSIV6qWNea-gzGzoHsz'
    appKey = 'oJBVUOcItn0essSFvY6tS77O'
    notify = false  # mail notifier , https://github.com/xCss/Valine/wiki
    verify = false # Verification code
    avatar = 'mm'
    placeholder = 'Please leave a message...'
    visitor = true

[params.blog]
    enable = true

[params.news]
    enable = true

[params.emails]
    enable = true

    
[params.copyright]
    enable = true
    text = "<a href=\"/trademark.html\">Trademark</a>&nbsp;&nbsp;<a href=\"/legalnotice.html\">Legal</a>&nbsp;&nbsp;<a href=\"/privacypolicy.html\">Privacy</a><br>Licensed under the<a>Apache License Version 2.0</a><br>Copyright © openLooKeng 2020. All rights reserved."

[languages.zh.params.copyright]
    enable = true
    text = "<a href=\"/zh-cn/trademark.html\">商标</a>&nbsp;&nbsp;<a href=\"/zh-cn/legalnotice.html\">法律声明</a>&nbsp;&nbsp;<a href=\"/zh-cn/privacypolicy.html\">隐私政策</a><br>版权所有 © openEuler 2020 保留一切权利 "

[markup.goldmark.renderer]
unsafe= true